{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v4.json", "dbt_version": "1.3.0", "generated_at": "2022-10-23T16:23:02.802367Z", "invocation_id": "f8c00c04-20d3-4e2f-a5a7-f3292c670a16", "env": {}}, "results": [{"status": "error", "timing": [], "thread_id": "Thread-1 (worker)", "execution_time": 0.5071573257446289, "adapter_response": {}, "message": "Database Error in model combined_attribution2 (models\\attribution\\attribution_models\\combined_attribution2.sql)\n  relation \"Postgres.ao_combined\" does not exist\n  LINE 13:    FROM \"acton\".\"Postgres\".\"ao_combined\" \n                   ^\n  compiled Code at target\\run\\acton_marketing_data\\models\\attribution\\attribution_models\\combined_attribution2.sql", "failures": null, "unique_id": "model.acton_marketing_data.combined_attribution2"}], "elapsed_time": 2.68424916267395, "args": {"write_json": true, "use_colors": true, "printer_width": 80, "version_check": true, "partial_parse": true, "static_parser": true, "profiles_dir": "C:\\Users\\JP\\Dropbox\\PC (3)\\Desktop\\Git\\generalsql-main", "send_anonymous_usage_stats": false, "event_buffer_size": 100000, "quiet": false, "no_print": false, "select": ["combined_attribution2"], "which": "run", "rpc_method": "run", "indirect_selection": "eager"}}